#FROM debian:stretch-slim
FROM ubuntu:14.04

MAINTAINER NGINX Docker Maintainers "docker-maint@nginx.com"

COPY tools/LuaJIT-2.0.5.tar.gz /home/software/
COPY tools/nginx-1.13.4.tar.gz /home/software/
COPY tools/v0.10.10.tar.gz /home/software/
COPY tools/v0.3.0.tar.gz /home/software/
COPY tools/openssl-1.0.2k.tar.gz /home/software/



RUN apt-get update \
	&& apt-get install --no-install-recommends --no-install-suggests -y g++ gcc make build-essential autoconf libtool libpcre3-dev asciidoc xmlto libev-dev libudns-dev automake libssl-dev zlib1g-dev \
	&& cd /home/software/ \
	&& tar -zxvf /home/software/LuaJIT-2.0.5.tar.gz \
	&& tar -zxvf /home/software/nginx-1.13.4.tar.gz \
	&& tar -zxvf /home/software/v0.10.10.tar.gz \
	&& tar -zxvf /home/software/v0.3.0.tar.gz \
	&& tar -zxvf /home/software/openssl-1.0.2k.tar.gz \
#	&& cd /home/software/openssl-1.0.2k \
#	&& ./config darwin64-x86_64-cc --prefix=/usr \
#	&& make && make install \

	&& cd /home/software/LuaJIT-2.0.5 \
	&& make PREFIX=/home/lib/lj2 && make install PREFIX=/home/lib/lj2 \
	&& export LUAJIT_LIB=/home/lib/lj2/lib/ \
	&& export LUAJIT_INC=/home/lib/lj2/include/luajit-2.0/




CMD ["/bin/bash"]